FROM node:22-alpine

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

ENV NODE_ENV=production

RUN npm run web:build

RUN npm prune --omit=dev

EXPOSE 3110

CMD ["npm", "run", "web:start"]