// File Path: src/workers/openai.worker.js

const { Worker } = require('bullmq');
const redisClient = require('../core/redis');
const OpenAiService = require('../services/OpenAiService');
const UserService = require('../services/UserService');
const ChatService = require('../services/ChatService');
const notifier = require('../utils/notifier.util');
const logger = require('../utils/logger.util');

/**
 * OpenAI Worker
 * The "Brain" of the background processing.
 * Listens to the openai-completions queue, interacts with OpenAI API,
 * updates the database, and notifies the user with the final answer.
 */

const openaiWorker = new Worker('openai-completions', async (job) => {
    const { userId, baleId, context, systemPrompt, messageId } = job.data;

    try {
        logger.info(`[OpenAiWorker] Processing job ${job.id} for user ${userId}`);

        // 1. Call OpenAI API through the service
        const aiResponse = await OpenAiService.generateChatCompletion(context, systemPrompt);

        if (!aiResponse.isSuccess) {
            // If it's a known error from the service, notify the user
            await notifier.sendMessageToUser(baleId, `⚠️ متاسفانه در پردازش پاسخ مشکلی پیش آمد: \n_${aiResponse.error}_`);
            return;
        }

        // 2. Persist the interaction in Chat History (Database)
        await ChatService.logMessage({
            userId,
            messageId: 0, // Generated by Assistant, no specific Bale ID yet
            replyToMessageId: messageId,
            role: 'assistant',
            content: aiResponse.content,
            tokens: aiResponse.tokens
        });

        // 3. Deduct tokens and update user stats
        // We use the real token usage returned by OpenAI API for billing accuracy
        await UserService.deductTokens(userId, aiResponse.tokens.total);
        await UserService.incrementSuccessfulRequests(userId);

        // 4. Send the result back to the user on Bale
        await notifier.sendMessageToUser(baleId, aiResponse.content);

        logger.info(`[OpenAiWorker] Job ${job.id} completed successfully.`);

    } catch (error) {
        logger.error(`[OpenAiWorker] Critical failure in job ${job.id}:`, error);
        // Throwing the error here tells BullMQ to retry the job based on backoff settings
        throw error;
    }
}, {
    connection: redisClient,
    // Concurrency: How many AI requests this worker handles at the same time.
    // For GPT-4o-mini/GPT-3.5, 5-10 is a safe starting point to avoid local memory spikes.
    concurrency: 5
});

// Event Listeners for Worker Status
openaiWorker.on('completed', (job) => {
    logger.info(`[OpenAiWorker] Job ${job.id} marked as COMPLETED.`);
});

openaiWorker.on('failed', (job, err) => {
    logger.error(`[OpenAiWorker] Job ${job.id} marked as FAILED after retries. Error: ${err.message}`);
});

module.exports = openaiWorker;