// File Path: src/utils/markdown.util.js

/**
 * Bale Markdown Parser Utility
 * OpenAI generates standard Markdown (e.g., **bold**, ### Headers).
 * Bale Messenger has a specific subset of Markdown support (requires spaces around symbols, no direct header support).
 * This utility ensures the AI output is correctly formatted for Bale without breaking code blocks.
 */

/**
 * Parses standard OpenAI markdown to Bale-compatible markdown.
 * * @param {string} text - The raw markdown text generated by OpenAI.
 * @returns {string} - The safely parsed text ready to be sent to Bale.
 */
const parseOpenAiToBaleMarkdown = (text) => {
    if (!text) return '';

    // Split the text by code blocks (```...```) to avoid altering code formatting
    // The regex captures the code blocks, so they will be included in the resulting array at odd indices.
    const parts = text.split(/(```[\s\S]*?```)/g);

    for (let i = 0; i < parts.length; i++) {
        // Only process standard text blocks (even indices in the split result)
        // Odd indices are the code blocks which must remain completely untouched.
        if (i % 2 === 0) {
            let part = parts[i];

            // 1. Convert Bold-Italic (***text***) to just Bale Bold
            // Bale doesn't handle nested formatting well.
            part = part.replace(/\*\*\*(.*?)\*\*\*/g, ' *$1* ');

            // 2. Convert Headers (### Header) to Bale Bold
            // Bale does not support HTML headers natively, so we emphasize them with bold.
            part = part.replace(/^(#{1,6})\s+(.+)$/gm, ' *$2* ');

            // 3. Convert Standard Bold (**text**) to Bale Bold (*text*)
            // Bale documentation explicitly states: "باید قبل از ستاره اول و بعد از ستاره دوم یک فاصله بگذارید"
            part = part.replace(/\*\*(.*?)\*\*/g, ' *$1* ');

            // 4. Convert Standard Italic (*text* or _text_) to Bale Italic (_text_)
            // We use negative lookbehinds/lookaheads to target single asterisks without breaking bold asterisks.
            part = part.replace(/(?<!\*)\*(?!\*)(.+?)(?<!\*)\*(?!\*)/g, ' _$1_ ');

            // 5. Clean up any double spaces generated by the safety padding above
            // Ensures the final text remains clean and readable
            part = part.replace(/ +/g, ' ');

            // Note: Links like [text](url) are natively supported by Bale, so no regex is needed for them.

            parts[i] = part;
        }
    }

    // Rejoin the parts (text and code blocks) and trim any trailing spaces
    return parts.join('').trim();
};

module.exports = {
    parseOpenAiToBaleMarkdown
};