// File Path: src/models/Transaction.js

const mongoose = require('mongoose');
const CONSTANTS = require('../config/constants');

/**
 * Transaction Schema
 * Handles all financial records including manual receipts, Bale Wallet, and ZarinPal.
 * Designed with sparse unique indexes to prevent double-spending vulnerabilities.
 */
const TransactionSchema = new mongoose.Schema({
    user: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
        required: true,
        index: true,
        description: 'Reference to the User who initiated the transaction'
    },
    amountIrt: {
        type: Number,
        required: true,
        min: [0, 'Amount cannot be negative'],
        description: 'Transaction amount in Iranian Toman (IRT)'
    },
    tokenAmount: {
        type: Number,
        required: true,
        min: [1, 'Token amount must be at least 1'],
        description: 'Number of AI tokens the user will receive upon successful payment'
    },
    paymentMethod: {
        type: String,
        enum: ['RECEIPT', 'BALE_WALLET', 'ZARINPAL'],
        required: true,
        description: 'The method used for this transaction'
    },
    status: {
        type: String,
        enum: Object.values(CONSTANTS.TRANSACTION_STATUS),
        default: CONSTANTS.TRANSACTION_STATUS.PENDING,
        index: true,
        description: 'Current status of the transaction (e.g., PENDING, SUCCESS, REJECTED)'
    },

    // --- Manual Receipt Specific Fields ---
    receiptPhotoId: {
        type: String,
        default: null,
        description: 'Bale file_id for the uploaded receipt photo'
    },
    adminNote: {
        type: String,
        default: null,
        description: 'Reason provided by admin if a manual receipt is REJECTED'
    },

    // --- Bale Wallet Specific Fields ---
    baleChargeId: {
        type: String,
        default: null,
        unique: true,
        sparse: true, // Only index if the field exists, allows multiple nulls
        description: 'Unique telegram_payment_charge_id from Bale Wallet successful payment'
    },

    // --- ZarinPal Specific Fields ---
    zarinpalAuthority: {
        type: String,
        default: null,
        unique: true,
        sparse: true,
        description: 'Unique authority code generated by ZarinPal'
    },
    zarinpalRefId: {
        type: String,
        default: null,
        description: 'Reference ID returned by ZarinPal after successful verification'
    }
}, {
    timestamps: true
});

// Compound index to quickly filter transactions by a specific user and status (useful for admin dashboard)
TransactionSchema.index({ user: 1, status: 1 });

const Transaction = mongoose.model('Transaction', TransactionSchema);

module.exports = Transaction;